### ISSUE TITLE
Quota Exceeded during setup of new project

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#198]
**Describe the bug**
During setup of a new project a quota exceeded error occured

Message:
_QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://tenant.sharepoint.com/sites/myproject/_api/web/lists/getbytitle('endringsanalyse')/fields?$select=id,internalname,schemaxml' exceeded the quota._

**To Reproduce**
Refresh the project site and run a project setup once more

**Expected behavior**
Setup should finish without failure

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/72531071-06841200-3871-11ea-9acc-0089e7b206f7.png)

**About your setup**
 - Browser [chrome]
 - Installed version [1.1.7]

**Additional context**

**Comment by pzljanb** [comment]
Happens also for newly created projects
Seems like the 'Create Project' functionality has been corrupted.

**Comment by olemp** [comment]
The root cause of this is exceeding of quota for local/session storage (example not related to Prosjektportalen: https://github.com/MetaMask/metamask-extension/issues/3071).

Provisioning uses http://github.com/Puzzlepart/sp-js-provisioning to do modifications that are not available using site design. This library (which we are maintaining) is using browser cache to improve performance, and in this case it's trying to store a value which is too large,

It's trying to save the `InternalName` and `SchemaXml` of all the fields in the list `Endringsanalyse` and it fails doing so. I have no idea why, as I've had no issues with this previously. We'll have a look at what we can do if this doesn't solve itself.

**Comment by pzljanb** [comment]
Restarted Chrome, and re-runned the project setup without any faults.
