### ISSUE TITLE
"Hent dokumentmal" not working with single folder in doc.library

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#319]
**Describe the bug**
The function of "Hent dokumentmal" that gives you the opportunity to select target folder for the copied file is not working with only a single folder in the document library.

**To Reproduce**

0. Start with a doc.library without any folders
1. Create one folder in the document library
2. Select a file to copy with the "Hent dokumentmal" function
3. Click 'Next'
4. Try to select your folder created in step 1 as the target folder
5. Cancel
6. Go thru step 1 to 4 ones more and verify that with two folders in place you can select target folder
7. Delete one of the folders and verify that ones again the target folder is not selectable with only one folder in your library

**Expected behavior**
Selection of target folder should be working with only one folder to select from.

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/94910140-9112ad00-04a4-11eb-84f9-f24e62ce4749.png)
![image](https://user-images.githubusercontent.com/58074707/94910152-95d76100-04a4-11eb-9d3b-bdd59810d2c1.png)

**About your setup**

- Browser [Chrome]
- Installed version [1.2.3]

**Additional context**
Only top level foldres can be selected. 
Has there been done any considerations around enabling a "browse folders" functionality that looks deeper than the first level of folders?

**Comment by olemp** [comment]
This is fixed in #376.

All we need to decide is what to call "Rotnivå".

If you have one folder, you can decide between that folder and root level (directly in the library, not in a folder). 

![image](https://user-images.githubusercontent.com/7606007/106472277-cd7e0600-64a2-11eb-8468-c1ff59c7ed18.png)


cc @pzljanb @tarjeieo

**Comment by olemp** [comment]
This is fixed in #376.

All we need to decide is what to call "Rotnivå".

If you have one folder, you can decide between that folder and root level (directly in the library, not in a folder). 

![image](https://user-images.githubusercontent.com/7606007/106472277-cd7e0600-64a2-11eb-8468-c1ff59c7ed18.png)


cc @pzljanb @tarjeieo

**Comment by tarjeieo** [comment]
How about using "Øverste nivå" as the name? Perhaps a more familiar term... "Root level" might be better in english though
