### ISSUE TITLE
No menu after selecting Opprett område(gruppenettsted) 

### ISSUE THREAD

**Issue by OsamaAlaydi** [Puzzlepart/prosjektportalen365#490]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs, please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x ] Bug

[x ] Question

#### Browser

[ ] Chrome

[ ] Internet Explorer

[x ] Edge

[ ] Safari

[ ] Other

#### Summary

Please summarize the issue.

#### Version

Please specify what version you are using: [ ]
1.2.8
You can find the version you are using in the bottom left corner of any page in the Project Portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
No menu after selecting Opprett område(gruppenettsted). Unable to create prosjekt
#### Observed Behavior

_If you are reporting an issue, please describe the behavior you observed when performing the action. If you are making a suggestion or asking a question, delete this section._

#### Steps to Reproduce

_If you are reporting an issue, please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making a suggestion or asking a question, delete this section._

**Comment by kiwihansen** [comment]
Hi Osama,

This is because you are on the targeted release from MS, which makes some significant changes to how SiteDesign is applied in the UI.

The work around for this is as follows:

Login to your sharepoint projectportal site with 
'Connect-PnPOnline -Url "https://yourtenant.sharepoint.com/sites/Prosjektportalen365" -UseWebLogin'
Run the following command and copy the value under Id
'Get-PnPSiteDesign'
It should be in this format: 32813b59-0ba6-463e-a4a2-66d27576426d
Use that to run the following command:
'Set-PnPHubSite -Identity "https://yourtenant.sharepoint.com/sites/Prosjektportalen365" -SiteDesignId 29550ab4-53d9-4aae-b7f0-54699bd06f93'

All new projects will now have the Project template applied automatically when they get assigned to the hub.

**Comment by tarjeieo** [comment]
As @kiwihansen mentions, the site template selector have been moved from being a pre-creation action to an action you can apply after the site has been created. This can be done manually by selecting "Apply a site template" ("Bruk en områdemal").
![image](https://user-images.githubusercontent.com/1837390/129148237-5a27340a-fbe1-4713-a67c-d9c8d2a31aa5.png)

As mentioned, this can be automated, so that all new sites within the hub will get the Prosjektområde template automatically applied. This will most likely be part of the next release.
