### ISSUE TITLE
Child project search not functioning as expected

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen365#759]
Added as high priority, as there are quite a few incoming and existing customers with many projects.

**Describe the bug**
When adding child projects to a program/parent project, the selected project does not persist when changing search query.

![image](https://user-images.githubusercontent.com/10527497/186399531-b5ba1d3d-5045-48c7-9e4a-e4f485ce7fa2.png)
Here, I search "Ny" and select "Nybygg Bikuben."

![image](https://user-images.githubusercontent.com/10527497/186399638-30371377-43c8-49d8-8807-7197d5c9c810.png)
I have **not** de-selected "Nybygg Bikuben," but the selected project has been changed.

When reverting the search to nothing, it will revert, unless I have selected something in the search

**To Reproduce**

1. Go to administration
2. Click on add project 
3. Select a project, then clear search box
4. Search a new project and select one of the results.
5. Add projects, and you will see there is a mis-match

**Expected behavior**
Selected projects should persist, regardless of change in search query.

**About your setup**

- Chrome
- Version 1.6.1 (from prosjektportalen tenant)

**Comment by tonnesr** [comment]
The issue was not with PP, but with the package @pnp/spfx-controls-react@1.11.0. Had to update the package to @pnp/spfx-controls-react@1.21.1 for the issue to be resolved.

**Comment by Remi749** [comment]
Good find 👍

**Comment by olemp** [comment]
> The issue was not with PP, but with the package `@pnp/spfx-controls-react@1.11.0`. Had to update the package to `@pnp/spfx-controls-react@1.21.1` for the issue to be resolved.

Deilig work

**Comment by tonnesr** [comment]
The larger issue was still present after updating the `@pnp/spfx-controls-react` package (even to the newest version).

To resolve the larger issue of selection not being kept when performing a search, I had to rewrite the whole component from scratch. 
I first tried to use a DetailsList instead of the pnp list, but since the pnp list uses DetailsList in the background, I had the exact same issues as before.

The way I solved it was by creating a new list component from scratch. I looks and works somewhat like DetailsList, so it should not be unfamiliar to anyone who uses SharePoint.

I made the new list component pretty generic (except for the name "ProjectTable"), so it should be easy to use other places in PP365.

**Comment by Remi749** [comment]
> The larger issue was still present after updating the `@pnp/spfx-controls-react` package (even to the newest version).
> 
> To resolve the larger issue of selection not being kept when performing a search, I had to rewrite the whole component from scratch. I first tried to use a DetailsList instead of the pnp list, but since the pnp list uses DetailsList in the background, I had the exact same issues as before.
> 
> The way I solved it was by creating a new list component from scratch. I looks and works somewhat like DetailsList, so it should not be unfamiliar to anyone who uses SharePoint.
> 
> I made the new list component pretty generic (except for the name "ProjectTable"), so it should be easy to use other places in PP365.

Great stuff, create a PR when you're ready 👍

**Comment by olemp** [comment]
> The larger issue was still present after updating the `@pnp/spfx-controls-react` package (even to the newest version).
> 
> To resolve the larger issue of selection not being kept when performing a search, I had to rewrite the whole component from scratch. I first tried to use a DetailsList instead of the pnp list, but since the pnp list uses DetailsList in the background, I had the exact same issues as before.
> 
> The way I solved it was by creating a new list component from scratch. I looks and works somewhat like DetailsList, so it should not be unfamiliar to anyone who uses SharePoint.
> 
> I made the new list component pretty generic (except for the name "ProjectTable"), so it should be easy to use other places in PP365.

We should avoid creating custom components from scratch if we can use a component from `office-ui-fabric-react` (or `@fluentui/react`). 

The selection are persisted in state, right? We should be able to ensure the correct selection for the `<DetailsList />` component then?

**Comment by tonnesr** [comment]
@olemp I tried a bunch of different methods for the state to be completely persistent with no luck. Others have had the same issue, but I could not find anyone that completely solved the issue. The closes I got was [this one](https://stackblitz.com/edit/react-ts-3shcme?file=FilteredDetailsList.tsx), which works pretty well. The only problem is that items that are not in the list after searching gets "unselected" until they are in the list again. 

For example (you can test this in the linked solution):
1. You have a list of four items: [ "Item 1", "Test 1", "Item 2", "Object 1" ].
2. You select all the items
3. The callback function and the internal state gets updated so that all items are selected.
4. You search for "Item" and only two items appear [ "Item 1", "Item 2" ].
5. The callback function and the internal state gets updated so that all
