### ISSUE TITLE
Improvements to Projecttimeline (tagging, descriptions/dependecies)

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#764]
**Describe the solution you'd like**

New functionality/improvements to projecttimeline and configuration
- Ability to tag a timeline item (taxonomy or choice)
- Description field for timeline item by default

This is funded by customer

**Comment by pzljanb** [comment]
- Add 'Category' to timeline configuration
  - Values:
       - Styring
       - Leveranse

![image](https://user-images.githubusercontent.com/58074707/188879945-c35efb0d-1ecc-405a-aa02-de6e5f920740.png)


Should be used for **filtering** and **grouping**

By default timeline webpart in projects should be grouped by 'Category' instead of todays 'Project title'

Webpart on Portfolio and in Parent projects should have 'Category' as **Filter** option.

![image](https://user-images.githubusercontent.com/58074707/188879345-affc49b9-c086-4e88-a61f-73c4641e6a1e.png)

**Comment by Remi749** [comment]
Here is an image of the new description and tag:
![image](https://user-images.githubusercontent.com/28678468/190670734-58b48004-8268-4fbb-962c-e127892e79bd.png)

Rounded the corners by 4px for the callout so it matches the tag and Microsofts new fluent ui style
